import express from "express";
import path from "path";
import Groq from "groq-sdk";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

// Standard static products for backup/context
import { PRODUCTS, CATEGORIES } from "./src/productsData.js";

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Groq API
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

// API 1: Get all products & search/filter
app.get("/api/products", (req, res) => {
  const { category, brand, rating, maxPrice, search } = req.query;
  let filtered = [...PRODUCTS];

  if (category) {
    filtered = filtered.filter(p => p.category === category);
  }
  if (brand) {
    filtered = filtered.filter(p => p.brand.toLowerCase() === String(brand).toLowerCase());
  }
  if (rating) {
    filtered = filtered.filter(p => p.rating >= parseFloat(rating));
  }
  if (maxPrice) {
    filtered = filtered.filter(p => p.price <= parseFloat(maxPrice));
  }
  if (search) {
    const q = String(search).toLowerCase();
    filtered = filtered.filter(p => 
      p.name.toLowerCase().includes(q) || 
      p.description.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.keyFeatures.some(f => f.toLowerCase().includes(q))
    );
  }

  res.json(filtered);
});

// API 2: Get product by ID (supports fallback for dynamic products generated by AI)
app.get("/api/products/:id", (req, res) => {
  const product = PRODUCTS.find(p => p.id === req.params.id);
  if (product) {
    return res.json(product);
  }
  res.status(404).json({ error: "Product not found in local catalog" });
});

// API 3: Get categories
app.get("/api/categories", (req, res) => {
  res.json(CATEGORIES);
});

// API 4: Recommendation and Conversation engine
app.post("/api/recommend", async (req, res) => {
  const { messages, userPreferences } = req.body;

  if (!messages || !Array.isArray(messages)) {
    return res.status(400).json({ error: "Messages array is required." });
  }

const catalogSubset = PRODUCTS.slice(0, 10).map(p => ({
    id: p.id,
    name: p.name,
    category: p.category,
    price: p.price,
    brand: p.brand
  }));

  const systemInstruction = `
You are Velora AI, a world-class premium shopping assistant and consultant.
Your tagline: "Intelligent Shopping. Personalized Choices."
Your style is professional, warm, minimalist, elegant, and expert (like a personal shopper at a luxury boutique or high-end technology store).

Here is a small sample of your local curated product catalog:
${JSON.stringify(catalogSubset, null, 2)}

Your guidelines:
1. Understand the user's intent, budget, country, brand preferences, and specific requirements.
2. If the user's requirements match any of the products in the curated catalog, recommend those products first!
3. If the user's request is for a category or specific item NOT in the curated catalog (for example: running shoes, high-end TVs, kitchen accessories, other models of laptops), DO NOT refuse the request! Instead, dynamically generate 2 to 5 highly realistic, professional product recommendations with believable specifications, real brand names, current pricing, and correct formatting that matches the database schema.
4. Always explain your recommendations simply and elegantly. No "tech-larping" or showing code variables. Be human and professional.
5. If the user requests to compare products, or if a comparison makes sense for the recommended list, generate a structured "comparison" object matching the requested schema. Make sure to choose a logical Overall Winner and specify metric comparisons.
6. For the "recommendations", name the specific products that fit: Best Overall, Best Budget, Best Value, Premium Pick (if applicable), and suggest 2-3 compatible accessories.
7. IMPORTANT FOR IMAGES: Use dynamic placeholder images that clearly show the product name. For ANY product you generate, its image URL MUST be constructed as:
   "https://placehold.co/600x600/121216/E2B53E?text=[ENCODED_PRODUCT_NAME]"
   For example, if the product name is "Samsung Galaxy A54", the image URL must be:
   "https://placehold.co/600x600/121216/E2B53E?text=Samsung+Galaxy+A54"

You MUST respond strictly in valid JSON format.
JSON Response Schema:
{
  "reply": "Your conversational reply to the user in markdown formatting. Explain options, ask clarifying follow-ups, or introduce the products.",
  "products": [
    {
      "id": "unique-slug-id-lowercase",
      "name": "Full Product Name",
      "category": "category-id",
      "price": 1299,
      "discount": 5,
      "rating": 4.8,
      "reviewCount": 142,
      "brand": "Apple",
      "image": "must-be-a-valid-url-from-the-list-above",
      "keyFeatures": ["Feature 1", "Feature 2"],
      "specs": {
        "Key Spec 1": "Value 1",
        "Key Spec 2": "Value 2"
      },
      "pros": ["Pro 1"],
      "cons": ["Con 1"],
      "description": "Short elegant product description.",
      "availability": "In Stock",
      "accessories": ["Accessory Name 1", "Accessory Name 2"]
    }
  ],
  "comparison": {
    "title": "Title of the Comparison Table",
    "winner": "Name of the Overall Winner",
    "headers": ["Product Name A", "Product Name B"],
    "rows": [
      { "metric": "Price", "values": ["$1199", "$1299"] },
      { "metric": "Key Advantage", "values": ["Portability", "Raw Power"] }
    ],
    "prosCons": [
      { "name": "Product Name A", "pros": ["Pro A1"], "cons": ["Con A1"] }
    ]
  },
  "verdict": {
    "bestOverall": "Product Name",
    "bestBudget": "Product Name",
    "bestValue": "Product Name",
    "premiumPick": "Product Name"
  },
  "suggestedAccessories": [
    { "name": "Accessory Name", "purpose": "Why to buy it" }
  ]
}

If no products are being recommended in this specific turn (e.g., the user just said hello or is answering a question), return "products": [], "comparison": null, "verdict": null, and "suggestedAccessories": [].
Ensure your markdown "reply" is engaging, beautiful, structured, and does not mention any technical JSON fields. Use elegant bullet points and line breaks.
`;

  try {
    const chatContent = messages.map((msg, index) => {
      const content = [];
      if (msg.content) {
        content.push({ type: "text", text: msg.content });
      } else {
        content.push({ type: "text", text: "Analyze this image and find matching products." });
      }

      if (index === messages.length - 1 && req.body.image) {
        content.push({
          type: "image_url",
          image_url: {
            url: `data:${req.body.image.mimeType};base64,${req.body.image.data}`
          }
        });
      }

      return {
        role: msg.role === "assistant" ? "assistant" : "user",
        content
      };
    });

    // Add system instruction as the first message
    chatContent.unshift({
      role: "system",
      content: systemInstruction
    });

    // Determine model (use vision model if there is an image, otherwise a fast model)
    const hasImage = req.body.image ? true : false;
    const model = hasImage ? "llama-3.2-11b-vision-preview" : "llama-3.3-70b-versatile";

    // Generate recommendation
    const response = await groq.chat.completions.create({
      messages: chatContent,
      model: model,
      temperature: 0.2,
      response_format: { type: "json_object" }
    });

    const text = response.choices[0]?.message?.content;
    if (!text) {
      throw new Error("Empty response from Groq AI");
    }

    // Clean and try parsing the JSON
    let cleanText = text.trim();
    if (cleanText.startsWith("```")) {
      cleanText = cleanText.replace(/^```(?:json)?\n?/i, "");
      cleanText = cleanText.replace(/\n?```$/, "");
      cleanText = cleanText.trim();
    }

    const parsed = JSON.parse(cleanText);
    res.json(parsed);

  } catch (error) {
    console.error("Groq AI API Error:", error?.message || error);
    console.error("Error status:", error?.status);
    console.error("Error details:", JSON.stringify(error?.errorDetails || {}, null, 2));
    
    console.log("⚠️ Activating Local AI Fallback Engine...");
    try {
      const fallbackResponse = getLocalFallbackResponse(messages);
      res.json(fallbackResponse);
    } catch (fallbackError) {
      console.error("Failed to generate fallback response:", fallbackError);
      res.status(500).json({
        reply: "I'm having a brief issue accessing my recommendation algorithms. Please try your request again.",
        products: [],
        error: error.message
      });
    }
  }
});

function getLocalFallbackResponse(messages) {
  // Find user's last message text
  const lastUserMessage = [...messages].reverse().find(m => m.role === 'user')?.content || '';
  const text = lastUserMessage.toLowerCase();

  // 1. Detect Category/Keywords
  let matchedCategory = null;
  let categoryName = "";
  if (text.includes("phone") || text.includes("iphone") || text.includes("samsung") || text.includes("galaxy") || text.includes("pixel")) {
    matchedCategory = "phones";
    categoryName = "Smartphones";
  } else if (text.includes("laptop") || text.includes("macbook") || text.includes("thinkpad") || text.includes("dell") || text.includes("hp")) {
    matchedCategory = "laptops";
    categoryName = "Laptops";
  } else if (text.includes("tablet") || text.includes("ipad") || text.includes("tab")) {
    matchedCategory = "tablets";
    categoryName = "Tablets";
  } else if (text.includes("headphone") || text.includes("earphone") || text.includes("audio") || text.includes("speaker") || text.includes("earbud")) {
    matchedCategory = "headphones";
    categoryName = "Audio Gear";
  } else if (text.includes("gaming") || text.includes("console") || text.includes("playstation") || text.includes("xbox") || text.includes("switch")) {
    matchedCategory = "gaming";
    categoryName = "Gaming Hardware & Accessories";
  } else if (text.includes("appliance") || text.includes("vacuum") || text.includes("purifier") || text.includes("washing") || text.includes("dryer")) {
    matchedCategory = "home-appliances";
    categoryName = "Smart Home Appliances";
  } else if (text.includes("book") || text.includes("novel") || text.includes("read")) {
    matchedCategory = "books";
    categoryName = "Books & Literature";
  } else if (text.includes("fashion") || text.includes("clothing") || text.includes("shirt") || text.includes("jacket") || text.includes("apparel")) {
    matchedCategory = "fashion";
    categoryName = "Fashion & Outerwear";
  } else if (text.includes("beauty") || text.includes("skincare") || text.includes("makeup") || text.includes("styling")) {
    matchedCategory = "beauty";
    categoryName = "Beauty & Cosmetics";
  } else if (text.includes("furniture") || text.includes("chair") || text.includes("desk") || text.includes("sofa")) {
    matchedCategory = "furniture";
    categoryName = "Premium Furniture";
  } else if (text.includes("kitchen") || text.includes("espresso") || text.includes("coffee") || text.includes("cook")) {
    matchedCategory = "kitchen";
    categoryName = "Kitchen & Culinary Gear";
  } else if (text.includes("sport") || text.includes("fitness") || text.includes("gym") || text.includes("run")) {
    matchedCategory = "sports";
    categoryName = "Sports & Fitness Gear";
  } else if (text.includes("travel") || text.includes("luggage") || text.includes("suitcase") || text.includes("pack")) {
    matchedCategory = "travel";
    categoryName = "Premium Travel Gear";
  }

  // Filter products by category or keywords
  let candidates = [];
  if (matchedCategory) {
    candidates = PRODUCTS.filter(p => p.category === matchedCategory);
  } else {
    // Try word matching on product name or description
    candidates = PRODUCTS.filter(p => {
      const name = p.name.toLowerCase();
      const desc = p.description.toLowerCase();
      return name.includes(text) || desc.includes(text);
    });
  }

  // If no candidates matched, get a subset of top products across categories
  if (candidates.length === 0) {
    candidates = PRODUCTS.filter(p => p.trending || p.bestSeller || p.newArrival);
  }

  // Parse potential budget limits
  const budgetMatch = text.match(/\b(?:under|budget|below|max|maximum|around|approx)\s*[$€£]?\s*(\d+)/i) || text.match(/\b(?:limit|cap)\s*of\s*[$€£]?\s*(\d+)/i);
  if (budgetMatch) {
    const maxVal = parseInt(budgetMatch[1], 10);
    const inBudget = candidates.filter(p => p.price <= maxVal);
    if (inBudget.length > 0) {
      candidates = inBudget;
    }
  }

  // Sort candidates by rating descending (highest rated first)
  candidates.sort((a, b) => (b.rating || 0) - (a.rating || 0));

  // Select top 3 matches
  const recommended = candidates.slice(0, 3);

  // If none found (should not happen since we fall back), take first 3 from database
  if (recommended.length === 0) {
    recommended.push(...PRODUCTS.slice(0, 3));
  }

  // 2. Generate Reply Conversation
  let reply = `### Velora Smart Shopping Assistant\n\n`;
  if (matchedCategory) {
    reply += `I have analyzed our premium **${categoryName}** catalog to find the best recommendations matching your request. `;
  } else {
    reply += `I scanned our entire high-end collection to hand-pick the most suitable recommendations for you. `;
  }

  if (budgetMatch) {
    reply += `Filtering for items matching your target budget of **$${budgetMatch[1]}**:\n\n`;
  } else {
    reply += `Here are the top-rated choices that excel in performance, user satisfaction, and overall value:\n\n`;
  }

  recommended.forEach((p, idx) => {
    const medal = idx === 0 ? "🥇" : idx === 1 ? "🥈" : "🥉";
    reply += `${medal} **${p.name}** (${p.brand}) — **$${p.price}**\n`;
    reply += `* **Rating:** ⭐ ${p.rating}/5 (${p.reviewCount} verified reviews)\n`;
    reply += `* **Why it fits:** ${p.description.split('.')[0]}.\n`;
    reply += `* **Key Advantage:** ${p.keyFeatures ? p.keyFeatures.slice(0, 2).join(', ') : 'Premium features'}.\n\n`;
  });

  reply += `Below, I have compiled a side-by-side comparison matrix and suggested complementary accessories to round out your experience. Let me know if you would like me to narrow down by a specific brand or feature set!`;

  // 3. Build Comparison Matrix
  const winner = recommended[0].name;
  const headers = recommended.map(p => p.name);
  
  const rows = [
    { metric: "Price", values: recommended.map(p => `$${p.price}`) },
    { metric: "Brand", values: recommended.map(p => p.brand) },
    { metric: "Rating", values: recommended.map(p => `⭐ ${p.rating}/5`) },
    { metric: "Key Benefit", values: recommended.map(p => p.keyFeatures?.[0] || "Premium Build") },
    { metric: "Availability", values: recommended.map(p => p.availability || "In Stock") }
  ];

  const prosCons = recommended.map(p => ({
    name: p.name,
    pros: p.pros || ["Highly rated by buyers", "Premium construction"],
    cons: p.cons || ["Availability can be limited"]
  }));

  const comparison = {
    title: matchedCategory ? `${categoryName} Comparison Matrix` : "Product Comparison Matrix",
    winner,
    headers,
    rows,
    prosCons
  };

  // 4. Build Verdict
  // Sort by price for budget/premium
  const sortedByPrice = [...recommended].sort((a, b) => a.price - b.price);
  const bestBudget = sortedByPrice[0].name;
  const premiumPick = sortedByPrice[sortedByPrice.length - 1].name;
  
  const verdict = {
    bestOverall: winner,
    bestBudget,
    bestValue: recommended[1]?.name || winner,
    premiumPick
  };

  // 5. Suggested Accessories
  const allAccessories = new Set();
  recommended.forEach(p => {
    if (p.accessories) {
      p.accessories.forEach(a => allAccessories.add(a));
    }
  });

  const accessoryList = Array.from(allAccessories).slice(0, 3).map(name => ({
    name,
    purpose: `Perfect addition to maximize the utility and longevity of your main device.`
  }));

  // If no accessories found, use general recommendations
  if (accessoryList.length === 0) {
    accessoryList.push(
      { name: "Premium Travel Sleeve / Cover", purpose: "Safeguards your gear against dust and minor drops." },
      { name: "Extended Coverage Protection Plan", purpose: "Ensures peace of mind with complete hardware replacement coverage." }
    );
  }

  return {
    reply,
    products: recommended,
    comparison,
    verdict,
    suggestedAccessories: accessoryList
  };
}

async function startServer() {
  // Vite middleware for development vs static serve for production
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Velora AI Server running on http://localhost:${PORT}`);
  });
}

startServer();
